# Generated by Django 3.0.7 on 2022-03-21 02:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20220321_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='symbol',
        ),
        migrations.AddField(
            model_name='meeting',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meeting',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='manager',
            field=models.ForeignKey(default='---------', on_delete=django.db.models.deletion.CASCADE, related_name='meetings_m', to='portfolio.Manager'),
        ),
    ]
