# Generated by Django 3.0.7 on 2022-03-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220321_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='updated_date',
            new_name='requested_date',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meetings_m', to='portfolio.Manager'),
        ),
    ]
