# Generated by Django 3.0.7 on 2022-03-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220321_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='recent_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='acquired_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='acquired_value',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recent_value',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
