# Generated by Django 3.0.7 on 2022-03-21 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220321_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='purchase_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='symbol',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='feedback',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_m', to='portfolio.Manager'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_t', to='portfolio.Task'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
