# Generated by Django 3.0.7 on 2022-03-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220321_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='zipcode',
        ),
    ]
